use crate::protocol::{DEFAULT_PROMPT_PACK_ID, PARTY_CHAOS_PROMPT_PACK_ID};

pub(crate) const SAFE_PROMPTS: &[&str] = &[
    "vampire dentist",
    "pizza lifeguard",
    "robot doing yoga",
    "haunted toaster",
    "wizard with stage fright",
    "moon on a first date",
    "cowboy accountant",
    "spaghetti tornado",
    "cat running a courtroom",
    "shark at a job interview",
    "grandma riding a comet",
    "turtle winning a marathon",
    "alien learning to skateboard",
    "snowman at the beach",
    "dragon selling insurance",
    "banana detective",
    "pirate in a library",
    "ghost taking a selfie",
    "octopus barista",
    "unicorn traffic cop",
    "angry refrigerator",
    "hamster business meeting",
    "skeleton birthday party",
    "penguin rock concert",
    "time traveler stuck in traffic",
    "ninja cooking pancakes",
    "giraffe in an elevator",
    "mermaid at a dentist",
    "monster babysitting",
    "wizard losing WiFi",
    "chair with stage dreams",
    "cloud walking a dog",
    "frog hosting a podcast",
    "mummy on vacation",
    "robot afraid of magnets",
    "potato superhero",
    "zombie ordering coffee",
    "castle with tiny legs",
    "fish driving a taxi",
    "bear at a tea party",
    "avocado running for mayor",
    "astronaut losing their keys",
    "cactus at a water park",
    "detective made of jelly",
    "sandwich giving a speech",
    "volcano taking a nap",
    "calendar with stage fright",
    "sock puppet news anchor",
    "mailbox joining a band",
    "pancake on a treasure hunt",
    "snail delivering pizza",
    "lamp training for a marathon",
    "toothbrush at a talent show",
    "spaceship stuck in a car wash",
    "cupcake lifting weights",
    "traffic cone at a fancy dinner",
    "backpack full of thunder",
    "submarine in a bathtub",
    "wizard opening a food truck",
    "moon wearing roller skates",
    "library book on vacation",
    "ice cream trying to hide",
    "robot learning ballet",
    "pillow solving a mystery",
    "rainbow in a board meeting",
    "pirate afraid of puddles",
    "sneaker running a bakery",
    "snow globe weather reporter",
    "accordion in outer space",
    "spoon winning a spelling bee",
    "hot dog at a chess match",
    "umbrella giving directions",
    "mountain learning karaoke",
    "pickle driving a race car",
    "kite stuck in an office",
    "waffle with a secret identity",
    "bubblegum building a rocket",
    "trophy going undercover",
    "pretzel teaching math class",
    "teapot at a dance contest",
    "broccoli bodyguard",
    "knight afraid of elevators",
    "yeti selling popsicles",
    "cowboy on a unicycle",
    "witch fixing a flat tire",
    "pharaoh at a grocery store",
    "viking assembling furniture",
    "genie stuck in a soda can",
    "centaur stuck in traffic",
    "troll collecting tolls politely",
    "fairy vacuuming the living room",
    "cyclops trying on sunglasses",
    "minotaur lost in a corn maze",
    "sphinx asking for directions",
    "golem watering houseplants",
    "kraken doing laundry",
    "sasquatch hitchhiking",
    "gargoyle watching a movie",
    "phoenix forgetting how to fly",
    "pirate map that lies",
    "treasure chest full of socks",
    "lantern afraid of moths",
    "cannon firing confetti",
    "balloon animal escape artist",
    "piñata hosting a reunion",
    "magician pulling a toaster",
    "juggler dropping planets",
    "tightrope walker carrying soup",
    "clown fixing a spaceship",
    "ringmaster training goldfish",
    "lobster fashion designer",
    "flamingo yoga instructor",
    "sloth racing a cheetah",
    "duck in a scuba suit",
    "panda learning to juggle",
    "bee running a lemonade stand",
    "seal balancing pancakes",
    "dolphin conducting an orchestra",
    "llama touring a museum",
    "hedgehog opening a spa",
    "a dog stuck in a sweater",
    "a cat walking its owner",
    "a birthday cake with too many candles",
    "a snowman in a hot tub",
    "an elephant hiding behind a flower",
    "a penguin carrying a beach umbrella",
    "a shark wearing floaties",
    "a dinosaur squeezing into a bus",
    "a ghost tangled in bedsheets",
    "a crab trying to clap",
    "a giraffe eating from a bird feeder",
    "a turtle winning a roller skate race",
    "a rabbit pulling a magician from a hat",
    "a dragon roasting marshmallows",
    "a sheep stuck to a balloon",
    "a squirrel with a shopping trolley",
    "a horse riding a tiny bicycle",
    "an octopus playing table tennis",
    "a chicken crossing a tightrope",
    "a mouse moving a huge piece of cheese",
    "a whale in a swimming pool",
    "a seal wearing oven mitts",
    "a fox stealing a garden hose",
    "a cow jumping a skipping rope",
    "a raccoon washing a pizza",
    "a monkey peeling a telephone",
    "a hippo on a water slide",
    "a caterpillar wearing too many shoes",
    "a peacock stuck in a revolving door",
    "a polar bear inside a refrigerator",
    "a castle made of sandwiches",
    "a tree growing doughnuts",
    "a house with wheels",
    "a staircase leading into a cloud",
    "a swimming pool full of jelly",
    "a car with square wheels",
    "a train going through a birthday cake",
    "a bridge made of spaghetti",
    "a boat with a giant spoon for an oar",
    "a playground on the moon",
    "a mountain wearing a woolly hat",
    "a rainbow tied in a knot",
    "a river flowing into a teacup",
    "a sun wearing sunglasses at night",
    "a tent blown inside out",
    "a lighthouse wearing a scarf",
    "a volcano full of popcorn",
    "a tunnel through a giant watermelon",
    "a cloud stuck in a chimney",
    "a fountain spraying noodles",
    "a pirate using a rubber duck as a boat",
    "a knight riding a rocking horse",
    "a wizard sweeping with a flying broom",
    "a superhero stuck in a tree",
    "a giant using a tiny toothbrush",
    "a mermaid wearing roller skates",
    "a robot trying to blow a bubble",
    "an astronaut fishing for stars",
    "a clown losing a giant shoe",
    "a ninja sneezing behind a curtain",
    "a detective following muddy footprints",
    "a queen sliding down a banister",
    "a chef flipping a pancake onto the ceiling",
    "a painter painting their own feet",
    "a firefighter watering a daisy",
    "a farmer pulling a giant carrot",
    "a lifeguard rescuing a rubber duck",
    "a magician sawing a sandwich in half",
    "a ballerina wearing flippers",
    "a diver finding a bathtub underwater",
    "a pizza with one enormous topping",
    "a banana wearing a raincoat",
    "a doughnut rolling down a hill",
    "a sandwich with a ladder inside",
    "an ice cream cone wearing mittens",
    "a pancake stuck to a frying pan",
    "a pineapple getting a haircut",
    "a carrot brushing its teeth",
    "a bowl of soup with a tiny sailboat",
    "a watermelon wearing a belt",
    "a strawberry hiding in a flowerpot",
    "a potato in a sleeping bag",
    "a jellybean driving a bumper car",
    "a cookie riding a glass of milk",
    "a lemon lifting a tiny dumbbell",
    "a broccoli treehouse",
    "an egg wearing a crash helmet",
    "a toast raft on a butter sea",
    "a noodle tied into a bow",
    "a chocolate bunny taking a bath",
    "an umbrella turned into a parachute",
    "a boot full of goldfish",
    "a backpack with butterfly wings",
    "a toothbrush cleaning a crocodile",
    "a kite carrying a picnic basket",
    "a sock used as a windsock",
    "a teddy bear sewing a person",
    "a broom sweeping a snowman",
    "a watering can watering another watering can",
    "a rocking chair on a skateboard",
    "a garden gnome trapped in a snow globe",
    "a rubber duck wearing a crown",
    "a clock with octopus arms",
    "a traffic cone used as a party hat",
    "a pair of slippers chasing a shoe",
    "a bicycle with a bathtub sidecar",
    "a drum full of bouncing frogs",
    "a tennis racket catching butterflies",
    "a ladder wearing boots",
    "a vacuum cleaner eating a scarf",
    "a snow angel shaped like a penguin",
    "a picnic invaded by giant ants",
    "a sandcastle with a real drawbridge",
    "a pillow fight on a trampoline",
    "a birthday party for a cactus",
    "a fishing rod catching an umbrella",
    "a treasure chest full of rubber ducks",
    "a snowball bigger than a house",
    "a paper airplane carrying a hamster",
    "a puddle with a diving board",
];

pub(crate) const CHAOS_PROMPTS: &[&str] = &[
    "traffic light tangled in balloons",
    "raccoon stealing a wedding cake",
    "robot vacuum chasing a mouse",
    "croissant that learned parkour",
    "wifi router caught in a fishing net",
    "pickle jar running for class president",
    "goose in a tuxedo arguing with a mirror",
    "speaker coughing up a flock of birds",
    "toaster oven opening a jazz club",
    "rubber duck detective solving cereal crimes",
    "elevator packed with penguins",
    "cactus getting tangled in a jump rope",
    "mime wrestling a giant balloon",
    "lasagna escaping a hungry dragon",
    "umbrella that refuses to open on purpose",
    "sock that became a motivational speaker",
    "vending machine attacked by squirrels",
    "paperclip building a tiny spaceship",
    "fridge magnet organizing a rebellion",
    "banana peel teaching defensive driving",
    "stapler biting a giant sandwich",
    "parking cone running a luxury hotel",
    "dust bunny training for the Olympics",
    "keyboard missing only the useful keys",
    "coffee mug floating in a sea of marshmallows",
    "charging cable tangled around a flamingo",
    "houseplant throwing a sofa out the window",
    "alarm clock trapped under twenty pillows",
    "shopping cart escaping the supermarket",
    "glitter spilling from a fire extinguisher",
    "doorbell interviewing strangers",
    "laundry basket sprouting tentacles",
    "remote control hiding from the couch",
    "spatula auditioning for a cooking show",
    "yogurt cup chased by a spoon",
    "garden gnome leading a heist",
    "bubble wrap popping for stress relief",
    "microwave timing a surprise party",
    "traffic jam that learned to dance",
    "lost sock opening a support group",
    "ceiling fan wearing six hats",
    "ice cube melting under pressure",
    "pencil eraser rubbing out a mountain",
    "sticky note covering a treasure map",
    "vacuum cleaner swallowing a magician's cape",
    "tea kettle screaming the weather",
    "puzzle piece hiding in a sandwich",
    "flashlight afraid of the dark",
    "rubber band catapulting a tomato",
    "giant coin crushing a plate of spaghetti",
    "snow shovel dreaming of summer",
    "parking meter eating a bag of popcorn",
    "fire hydrant gossiping with dogs",
    "mailbox overflowing with rubber ducks",
    "doormat surfing down a staircase",
    "coat hanger modeling haute couture",
    "toothbrush racing dental floss",
    "salt shaker making a tiny snowstorm",
    "pepper mill sneezing on a birthday cake",
    "napkin folded into a flying dragon",
    "straw trapped inside a giant coconut",
    "plastic fork hosting fine dining",
    "paper bag chased by a leaf blower",
    "tape dispenser wrapping a mummy",
    "scissors dueling a lobster",
    "glue stick stuck to a walrus",
    "ruler sword-fighting a baguette",
    "compass pointing toward snacks",
    "thermometer stuck in a snowman's mouth",
    "hourglass running late again",
    "calendar flipping out midweek",
    "bubble wand casting party spells",
    "hula hoop orbiting a boardroom",
    "yo-yo dangling a tiny astronaut",
    "frisbee delivering office memos",
    "beach ball bouncing through customs",
    "trampoline launching a bathtub",
    "scooter commuting through a museum",
    "skateboard rolling through a car wash",
    "roller skate auditioning for ballet",
    "unicycle chased by three bowling balls",
    "kayak paddling through a cubicle",
    "surfboard riding a wave of baked beans",
    "snowboard racing a runaway sled",
    "parachute landing in a meeting",
    "telescope spying on leftovers",
    "microscope examining a dancing flea",
    "binoculars watching the microwave",
    "megaphone whispering politely",
    "harmonica interrupting elevator music",
    "kazoo leading a serious meeting",
    "tambourine announcing lunch break",
    "maraca bouncing inside a washing machine",
    "xylophone falling down the stairs",
    "bagpipe inflating a bouncy castle",
    "tuba stuck in a revolving door",
    "accordion squeezing through a cat flap",
    "banjo playing itself with spider legs",
    "ukulele serenading a vending machine",
    "drumstick conducting kitchen chaos",
    "cymbal crashing a book club",
    "trumpet waking the neighborhood politely",
    "flute stuck in a birdhouse",
    "violin crying over spilled soup",
    "piano trapped on an escalator",
    "guitar stuck in a giant spiderweb",
    "amp turning whispers into announcements",
    "DJ booth mixing grocery lists",
    "karaoke machine forgetting the lyrics",
    "disco ball hatching a shiny chicken",
    "whiteboard riding an eraser like a surfboard",
    "a goose driving a monster truck",
    "a dragon stuck in a vending machine",
    "a shark delivering a pizza underwater",
    "a snail towing a caravan of elephants",
    "a flamingo wearing four roller skates",
    "a hippo hiding inside a wedding cake",
    "a spider knitting a sweater for a fly",
    "a gorilla using a banana as a telescope",
    "a goldfish walking a shark on a leash",
    "a penguin melting an igloo with a hairdryer",
    "a rooster laying a disco ball",
    "a crocodile zipped inside a sleeping bag",
    "a giraffe using a cloud as a pillow",
    "a walrus balancing a washing machine",
    "a jellyfish holding a birthday balloon",
    "a kangaroo with a trampoline in its pouch",
    "a chameleon stuck on a checkerboard",
    "a lobster cutting a giant ribbon",
    "a bear squeezing honey from a bee",
    "a frog with a fly stuck to its umbrella",
    "a duck leading a parade of bathtubs",
    "a turtle wearing a tent as a shell",
    "a hedgehog popping a bouncy castle",
    "an octopus wrapping eight presents at once",
    "a moose trying to use a revolving door",
    "a skunk painting a zebra",
    "a bat hanging from a ceiling fan",
    "a cow being abducted by a giant spoon",
    "a sheep unravelling like a ball of wool",
    "a squirrel launching an acorn into space",
    "a haunted toaster spitting ghost toast",
    "a refrigerator wearing ice skates",
    "a sofa giving birth to loose change",
    "a wardrobe swallowing a coat hanger",
    "a toilet floating away on balloons",
    "a vacuum cleaner stuck in a spaghetti tornado",
    "a washing machine full of treasure",
    "a lawn mower giving a lion a haircut",
    "a bathtub racing a speedboat",
    "a lampshade used as a satellite dish",
    "a chandelier tangled in a giant spiderweb",
    "a door knocking on a person",
    "a carpet rolling up a burglar",
    "a curtain hiding a herd of giraffes",
    "a bunk bed on a unicycle",
    "a doorbell squirting mustard",
    "a barbecue grilling an iceberg",
    "a fence jumping over a horse",
    "a microwave shrinking a dinosaur",
    "a bookshelf overflowing with snakes",
    "a moon made of melted cheese",
    "a volcano sneezing out beach balls",
    "a tornado wearing a tutu",
    "a waterfall flowing into a giant boot",
    "a rainbow being pulled out of a toaster",
    "a cloud wringing out a wet person",
    "a sun roasting a marshmallow moon",
    "a mountain zipped open like a suitcase",
    "a forest of giant paintbrushes",
    "a desert with a bathtub oasis",
    "a planet caught in a basketball hoop",
    "an iceberg towing a tropical island",
    "a lightning bolt stuck in a jar",
    "a tidal wave of rubber ducks",
    "a snowstorm inside a fish tank",
    "a drawbridge made of giant teeth",
    "a ferris wheel full of washing machines",
    "a roller coaster through a bowl of soup",
    "a skyscraper tied in a knot",
    "a swimming pool wearing a swimming cap",
    "a wizard accidentally turning into a mop",
    "a ghost stuck in a vacuum cleaner bag",
    "a pirate surfing on a treasure chest",
    "a knight jousting with a giant toothbrush",
    "a vampire biting a watermelon",
    "a mummy unwrapping a birthday present",
    "a werewolf stuck in a dog cone",
    "a mermaid fishing for a fisherman",
    "a giant using a bus as a roller skate",
    "an alien trying to hatch a football",
    "a robot rusting in a bubble bath",
    "a witch flying on a leaf blower",
    "a fairy stuck in a bubblegum bubble",
    "a troll tickling a bridge",
    "a cyclops wearing a magnifying glass",
    "a centaur putting on a pair of jeans",
    "a unicorn sharpening its horn in a sharpener",
    "a zombie chasing a runaway brain",
    "a genie emerging from a ketchup bottle",
    "a dragon blowing balloon animals",
    "a pizza folding itself into a paper airplane",
    "a hot dog walking six tiny sausages",
    "a cucumber riding a pickle submarine",
    "a spaghetti monster stuck in a colander",
    "a pineapple juggling coconuts",
    "a giant pea chasing a fork",
    "a taco using lettuce as a parachute",
    "a doughnut filling its hole with a spare tire",
    "a pancake using butter as ice skates",
    "a soup bowl eating a spoon",
    "a popcorn avalanche burying a cinema",
    "a marshmallow trying to put out a campfire",
    "a birthday cake blowing out its own candles",
    "a cheese wedge trapping a giant mouse",
    "a cupcake wearing a traffic cone",
    "a jelly castle wobbling in the wind",
    "a fried egg used as a flying saucer",
    "a pretzel rescuing a drowning noodle",
    "a banana peel slipping on a person",
    "a pear stuck in an apple costume",
    "an astronaut mowing the moon",
    "a chef whisking a tornado",
    "a magician pulling a bathtub from a hat",
    "a dentist cleaning a zipper's teeth",
    "a lifeguard swimming through jelly",
    "a painter brushing a rainbow's teeth",
    "a firefighter spraying confetti at a dragon",
    "a ballet dancer balancing on a bowling ball",
    "a marching band stuck in a revolving door",
    "a snorkeller exploring a giant teapot",
    "a football match inside a snow globe",
    "a basketball hoop running away from the ball",
    "a bowling pin throwing a tiny person",
    "a golf ball hatching a dragon",
    "a tennis match between two volcanoes",
    "a skateboard with spaghetti wheels",
    "a parachute made of giant underpants",
    "a trampoline catching a falling moon",
    "a tug of war with a giant noodle",
];

struct PromptPack {
    id: &'static str,
    prompts: &'static [&'static str],
}

const PROMPT_PACKS: &[PromptPack] = &[
    PromptPack {
        id: DEFAULT_PROMPT_PACK_ID,
        prompts: SAFE_PROMPTS,
    },
    PromptPack {
        id: PARTY_CHAOS_PROMPT_PACK_ID,
        prompts: CHAOS_PROMPTS,
    },
];

pub(crate) fn prompt_pack_prompts(prompt_pack_id: &str) -> Option<&'static [&'static str]> {
    PROMPT_PACKS
        .iter()
        .find(|pack| pack.id == prompt_pack_id)
        .map(|pack| pack.prompts)
}

#[cfg(test)]
mod tests {
    use super::{prompt_pack_prompts, CHAOS_PROMPTS, PROMPT_PACKS, SAFE_PROMPTS};
    use crate::protocol::{DEFAULT_PROMPT_PACK_ID, PARTY_CHAOS_PROMPT_PACK_ID};
    use std::collections::HashSet;

    const MIN_PROMPTS_PER_PACK: usize = 100;
    const EXPECTED_SAFE_PROMPT_COUNT: usize = 240;
    const EXPECTED_CHAOS_PROMPT_COUNT: usize = 240;

    fn assert_pack_quality(id: &str, prompts: &[&str]) {
        assert!(!prompts.is_empty(), "prompt pack {id} must be non-empty");
        assert!(
            prompts.len() >= MIN_PROMPTS_PER_PACK,
            "prompt pack {id} has {} prompts; expected at least {MIN_PROMPTS_PER_PACK}",
            prompts.len()
        );

        let mut seen = HashSet::new();
        for prompt in prompts {
            assert!(
                prompt.chars().count() <= crate::protocol::MAX_GUESS_LEN,
                "prompt must fit in a title: {prompt}"
            );
            let normalized = prompt.trim().to_ascii_lowercase();
            assert!(
                !normalized.is_empty(),
                "prompt pack {id} contains an empty prompt"
            );
            assert!(
                seen.insert(normalized),
                "prompt pack {id} has duplicate prompt: {prompt}"
            );
        }
    }

    #[test]
    fn prompt_packs_are_non_empty_unique_and_keep_expected_counts() {
        assert_eq!(PROMPT_PACKS.len(), 2);
        assert_pack_quality(DEFAULT_PROMPT_PACK_ID, SAFE_PROMPTS);
        assert_pack_quality(PARTY_CHAOS_PROMPT_PACK_ID, CHAOS_PROMPTS);
        assert_eq!(SAFE_PROMPTS.len(), EXPECTED_SAFE_PROMPT_COUNT);
        assert_eq!(CHAOS_PROMPTS.len(), EXPECTED_CHAOS_PROMPT_COUNT);

        assert_eq!(
            prompt_pack_prompts(DEFAULT_PROMPT_PACK_ID),
            Some(SAFE_PROMPTS)
        );
        assert_eq!(
            prompt_pack_prompts(PARTY_CHAOS_PROMPT_PACK_ID),
            Some(CHAOS_PROMPTS)
        );
        assert!(prompt_pack_prompts("unknown").is_none());
    }
}
